### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tejush1998** [samj1912/fbrecog#6]
print(recognize(path,access_token,cookie,fb_dtsg))
  File "/Library/Python/2.7/site-packages/fbrecog/__init__.py", line 23, in recognize
    post_id = graph.post( path = 'me/photos', source = open(path, 'rb'))['id']
IOError: [Errno 2] No such file or directory: 'received_151299858624740.jpeg'
TEJUSHs-MacBook-Air:facematch-master tejushsinghrandhaawaa$ python tej.py
Traceback (most recent call last):
  File "tej.py", line 7, in <module>
    print(recognize(path,access_token,cookie,fb_dtsg))
  File "/Library/Python/2.7/site-packages/fbrecog/__init__.py", line 23, in recognize
    post_id = graph.post( path = 'me/photos', source = open(path, 'rb'))['id']
  File "/Library/Python/2.7/site-packages/facepy/graph_api.py", line 95, in post
    retry=retry
  File "/Library/Python/2.7/site-packages/facepy/graph_api.py", line 332, in _query
    return load(method, url, data)[0]
  File "/Library/Python/2.7/site-packages/facepy/graph_api.py", line 288, in load
    result = self._parse(response.content)
  File "/Library/Python/2.7/site-packages/facepy/graph_api.py", line 403, in _parse
    raise exception(**self._get_error_params(data))
facepy.exceptions.OAuthError: [200] (#200) Requires extended permission: publish_actions

**Comment by sambhav** [comment]
It is because you haven't given post permissions while obtaining the graph api token
